### ISSUE TITLE
The tool can't see the source path on Unix systems

### ISSUE THREAD

**Issue by Fraizeraust** [Saibamen/ReactOS-Translation-Tool#1]
On Windows platforms the ReactOS Translation Tool can check the source directory path while on *nix (i.e Linux) it raises an error that the path couldn't be found. Not sure if it is my problem or the translation tool being bugged, the actual ReactOS source code directory is on my `/home` path while the tool source code is on `/opt/lampp/htdocs` (I actually use XAMPP to localhost the tool). 

By the way, I'm using Linux Mint 18.3 "Sylvia" in case you're asking me which OS I use.

**Comment by Saibamen** [comment]
What error occurs?

Can you paste your current $ROSDir value from config.php?

**Comment by Fraizeraust** [comment]
$ROSDir value:
`$ROSDir = '/home/borealis/ReactOS/Source/reactos';`
"reactos" source code contents:
https://imgur.com/a/zqsMJ
And this is what the ROS tool outputs:
https://imgur.com/a/1obrP

I double checked both the XAMPP and the ROS tool setup twice and couldn't find any issues or the like. I wonder what the cause could be, whether if it's from my side or something in your code process the *nix directory paths wrongly.

**Comment by Saibamen** [comment]
Can you check latest code from Master branch? c3b4ff9

**Comment by Fraizeraust** [comment]
I amended your latest commit branch, the issue still persists. :(

**Comment by Fraizeraust** [comment]
I assume the problem could also be caused by the wrong set of permissions of some related folders such as being the ReactOS source code folder and the ROS translation tool. I cannot judge though if it is really true.

I discussed about the issue on ReactOS forums ([link](https://www.reactos.org/forum/viewtopic.php?f=45&t=16946)), can you check if the permissions of the folders I posted are alright?

**Comment by Fraizeraust** [comment]
The issue has been fixed! The mere problem was that XAMPP used a kind of different username and usergroup for Apache thus it could not read the contents of ReactOS source code due to lack of required permission rights. 

A workaround on `/opt/lampp/etc/httpd.conf` fixed the problem for me thanks to Thomas Faber, [link](https://www.reactos.org/forum/viewtopic.php?p=129826#p129826). Now I will close the report as conclusion being **fixed**.
