### ISSUE TITLE
Uncaught ErrorException: preg_match_all()

### ISSUE THREAD

**Issue by gonzoMD** [Saibamen/ReactOS-Translation-Tool#8]
When trying to search for missing translation strings in German language, I get the following error message:

`Fatal error: Uncaught ErrorException: preg_match_all(): Compilation failed: unrecognized character follows \ at offset 18 in C:\xampp\htdocs\rtt\diff.php:102 Stack trace: #0 [internal function]: exceptions_error_handler(2, 'preg_match_all(...', 'C:\\xampp\\htdocs...', 102) #1 C:\xampp\htdocs\rtt\diff.php(102): preg_match_all('/^(?!FONT|\\s*\\*...', 'LANGUAGE LANG_E...', NULL) #2 C:\xampp\htdocs\rtt\diff.php(158): diff_versions('LANGUAGE LANG_E...', '/* German langu...') #3 {main} thrown in C:\xampp\htdocs\rtt\diff.php on line 102`

Environment: XAMPP 8.0.3

**Comment by Saibamen** [comment]
Should be fixed now
